# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignore:
      - dependency-name: "express"
        versions: ["4.x"]
      - dependency-name: "react"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      schedule.day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      schedule.day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3

      
