# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "golang"
    allow:
      - dependency-type: "all"
    actions:
      - label: "security-scan"
        type: "start"
        command:
          script: |
            docker pull aquasec/trivy
            docker run --rm -v $(pwd):/work aquasec/trivy --exit-code 0 --severity HIGH --no-progress --format json -o trivy_results.json
      - label: "security-scan"
        type: "wait"
        if-no-changes: true
      - label: "security-scan"
        type: "complete"
        if-changed: "Dockerfile*"


      
