name: Environment
on:
  push:
  workflow_dispatch:
env:
  NODE_ENV: you can see it
  NODE_SECRET: ${{ secrets.GH_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets usage
        run: |
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.NODE_SECRET }}"

  
