name: Environment
on:
  push:
  workflow_dispatch:
env:
  NODE_PASSWORD: 123456789
  NODE_SECRET: ${{ secrets.GH_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install truffleHog
        run: |
          pip install truffleHog
      - name: Scan for secrets in .env file
        run: |
          trufflehog --regex --entropy=True .env
      - name: Secrets usage
        run: |
          echo "${{ env.NODE_PASSWORD }}"
          echo "${{ env.NODE_SECRET }}"
