name: Environment
on:
  push:
  workflow_dispatch:
env:
  NODE_PASSWORD: 123456789
  NODE_SECRET: ${{ secrets.GH_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.78.0       
      - name: Secrets usage
        run: |
          echo "${{ env.NODE_PASSWORD }}"
          echo "${{ env.NODE_SECRET }}"
